function frontend
% ================================================================
% SHANNON-FANO DIGITAL COMMUNICATION
% FRONTEND - TRANSMITTER AND RECEIVER
% ================================================================

clc;

%% ================================================================
% MAIN WINDOW
% ================================================================

fig = uifigure( ...
    'Name','Digital Communication - Shannon Fano', ...
    'Position',[100 80 1200 700]);

%% ================================================================
% TITLE
% ================================================================

uilabel(fig, ...
    'Text','DIGITAL COMMUNICATION SYSTEM', ...
    'Position',[50 650 1100 35], ...
    'FontSize',24, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','center');

uilabel(fig, ...
    'Text','Shannon-Fano Text Compression + CRC Error Detection', ...
    'Position',[50 620 1100 25], ...
    'FontSize',14, ...
    'HorizontalAlignment','center');

%% ================================================================
% TRANSMITTER PANEL
% ================================================================

txPanel = uipanel(fig, ...
    'Title','TRANSMITTER', ...
    'FontSize',16, ...
    'FontWeight','bold', ...
    'Position',[40 250 500 340]);

uilabel(txPanel, ...
    'Text','Enter Message:', ...
    'Position',[25 260 150 25], ...
    'FontSize',14);

messageBox = uitextarea(txPanel, ...
    'Position',[25 190 450 65], ...
    'Value',{'GOOD MORNING'}, ...
    'FontSize',14);

transmitButton = uibutton(txPanel, ...
    'push', ...
    'Text','TRANSMIT', ...
    'Position',[155 135 190 40], ...
    'FontSize',16, ...
    'FontWeight','bold');

uilabel(txPanel, ...
    'Text','Original Bits:', ...
    'Position',[25 85 150 25], ...
    'FontSize',13);

originalBitsLabel = uilabel(txPanel, ...
    'Text','-', ...
    'Position',[180 85 250 25], ...
    'FontSize',13, ...
    'FontWeight','bold');

uilabel(txPanel, ...
    'Text','Compressed Bits:', ...
    'Position',[25 55 150 25], ...
    'FontSize',13);

compressedBitsLabel = uilabel(txPanel, ...
    'Text','-', ...
    'Position',[180 55 250 25], ...
    'FontSize',13, ...
    'FontWeight','bold');

uilabel(txPanel, ...
    'Text','Compression Ratio:', ...
    'Position',[25 25 150 25], ...
    'FontSize',13);

compressionLabel = uilabel(txPanel, ...
    'Text','-', ...
    'Position',[180 25 250 25], ...
    'FontSize',13, ...
    'FontWeight','bold');

%% ================================================================
% CHANNEL PANEL
% ================================================================

channelPanel = uipanel(fig, ...
    'Title','DIGITAL CHANNEL', ...
    'FontSize',16, ...
    'FontWeight','bold', ...
    'Position',[555 390 600 200]);

uilabel(channelPanel, ...
    'Text','TRANSMISSION STATUS', ...
    'Position',[25 130 550 30], ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','center');

channelStatus = uilabel(channelPanel, ...
    'Text','Waiting for transmission...', ...
    'Position',[25 85 550 35], ...
    'FontSize',17, ...
    'HorizontalAlignment','center');

channelInfo = uilabel(channelPanel, ...
    'Text','', ...
    'Position',[25 35 550 35], ...
    'FontSize',13, ...
    'HorizontalAlignment','center');

%% ================================================================
% RECEIVER PANEL
% ================================================================

rxPanel = uipanel(fig, ...
    'Title','RECEIVER', ...
    'FontSize',16, ...
    'FontWeight','bold', ...
    'Position',[555 250 600 130]);

uilabel(rxPanel, ...
    'Text','Received Message:', ...
    'Position',[25 70 180 25], ...
    'FontSize',13);

receivedMessageLabel = uilabel(rxPanel, ...
    'Text','Waiting...', ...
    'Position',[210 70 350 25], ...
    'FontSize',14, ...
    'FontWeight','bold');

uilabel(rxPanel, ...
    'Text','CRC Status:', ...
    'Position',[25 35 150 25], ...
    'FontSize',13);

crcLabel = uilabel(rxPanel, ...
    'Text','Waiting...', ...
    'Position',[210 35 350 25], ...
    'FontSize',13, ...
    'FontWeight','bold');

%% ================================================================
% ERROR STATUS
% ================================================================

statusPanel = uipanel(fig, ...
    'Title','RECEIVER STATUS', ...
    'FontSize',16, ...
    'FontWeight','bold', ...
    'Position',[40 70 1115 150]);

errorLabel = uilabel(statusPanel, ...
    'Text','READY', ...
    'Position',[25 75 1060 40], ...
    'FontSize',20, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','center');

errorCountLabel = uilabel(statusPanel, ...
    'Text','Channel Errors: -', ...
    'Position',[25 30 1060 30], ...
    'FontSize',14, ...
    'HorizontalAlignment','center');

%% ================================================================
% TRANSMIT BUTTON
% ================================================================

transmitButton.ButtonPushedFcn = @transmitMessage;

%% ================================================================
% TRANSMISSION FUNCTION
% ================================================================

    function transmitMessage(~,~)

        % ---------------------------------------------------------
        % Get message
        % ---------------------------------------------------------

        inputValue = messageBox.Value;

        if isempty(inputValue)

            uialert(fig, ...
                'Please enter a message.', ...
                'Input Required');

            return;

        end

        message = char(strjoin(inputValue,' '));

        if isempty(strtrim(message))

            uialert(fig, ...
                'Please enter a valid message.', ...
                'Input Required');

            return;

        end

        % ---------------------------------------------------------
        % Update transmitter
        % ---------------------------------------------------------

        channelStatus.Text = ...
            'Processing Shannon-Fano compression...';

        channelInfo.Text = ...
            'Please wait...';

        receivedMessageLabel.Text = ...
            'Transmitting...';

        crcLabel.Text = ...
            'Checking...';

        errorLabel.Text = ...
            'TRANSMITTING...';

        errorCountLabel.Text = ...
            'Channel Errors: Processing...';

        drawnow;

        % ---------------------------------------------------------
        % Run backend
        % ---------------------------------------------------------

        results = backend(message);

        % ---------------------------------------------------------
        % Update transmitter information
        % ---------------------------------------------------------

        originalBitsLabel.Text = ...
            num2str(results.originalBits);

        compressedBitsLabel.Text = ...
            num2str(results.compressedBits);

        compressionLabel.Text = ...
            sprintf('%.3f : 1', ...
            results.compressionRatio);

        % ---------------------------------------------------------
        % Channel status
        % ---------------------------------------------------------

        channelStatus.Text = ...
            'Transmission completed';

        channelInfo.Text = sprintf( ...
            'Frame Size: %d bits', ...
            length(results.transmittedFrame));

        % ---------------------------------------------------------
        % Receiver
        % ---------------------------------------------------------

        if results.crcValid

            receivedMessageLabel.Text = ...
                results.decodedMessage;

            crcLabel.Text = ...
                'PASS';

            errorLabel.Text = ...
                '✓ MESSAGE RECEIVED SUCCESSFULLY';

            errorCountLabel.Text = sprintf( ...
                'Channel Errors: %d', ...
                results.numberOfErrors);

        else

            receivedMessageLabel.Text = ...
                'MESSAGE REJECTED';

            crcLabel.Text = ...
                'FAIL';

            errorLabel.Text = ...
                '✗ TRANSMISSION ERROR DETECTED';

            errorCountLabel.Text = sprintf( ...
                'Channel Errors: %d', ...
                results.numberOfErrors);

        end

        % ---------------------------------------------------------
        % Update screen
        % ---------------------------------------------------------

        drawnow;

    end

end